services:
  lackey:
    platform: linux/amd64
    container_name: lackey
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5901:5901"
      - "8080:8080"
    environment:
      VNC_PASSWORD: asdfasdf
      DISPLAY: :1
    networks:
      - lackey
networks:
  lackey: